services:
  airflow-webserver:
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret_key
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: "airflow webserver"
    depends_on:
      - airflow-scheduler

  airflow-scheduler:
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
    command: "airflow scheduler"
    depends_on:
      - airflow-webserver

  airflow-worker:
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
    command: "airflow worker"
    depends_on:
      - airflow-webserver
